name: Terraform Validate

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "${{ secrets.AWS_REGION }}"

jobs:
  terraform_validate:
    name: "Validate Terraform Configuration"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Check Terraform files
      run: |
        if ! grep -q 'backend "s3"' *.tf; then
          echo "Error: AWS S3 backend configuration not found"
          exit 1
        fi
        if ! grep -q 'bucket' *.tf || ! grep -q 'region' *.tf || ! grep -q 'dynamodb_table' *.tf || ! grep -q 'key' *.tf; then
          echo "Error: Missing required backend configuration elements"
          exit 1
        fi
        echo "Terraform files check passed"

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate
